build:
  maxIssues: 0

config:
  validation: true

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true
  exclude:
    - "TxtOutputReport"

style:
  MagicNumber:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - "Composable"

performance:
  active: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
